openapi: 3.0.3
info:
  title: Recently Viewed Products API
  version: 1.0.0
paths:
  /api/v1/users/{userId}/recentlyViewed:
    get:
      summary: Get recently viewed products
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of recently viewed products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    productId:
                      type: string
                    timestamp:
                      type: string
                      format: date-time
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
